/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)

    id("org.jetbrains.kotlin.kapt") version "1.5.20"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("io.vertx:vertx-core:4.5.8")
    implementation("io.vertx:vertx-web-client:4.4.0")
    implementation("org.xerial:sqlite-jdbc:3.41.2.2")
    // implementation("io.vertx:vertx-lang-kotlin-coroutines:4.5.8")
    implementation("io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-aarch_64")
    implementation("de.mkammerer:argon2-jvm:2.11")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(21)
//    }
    toolchain {
        languageVersion =  JavaLanguageVersion.of(8)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.amphi.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "com.amphi.AppKt"
            
        )
    }
      archiveFileName.set("server.jar")
}